## REMEMBER TO SET UP YOUR GITHUB REPO FOR TRAVIS
## Go to: https://travis-ci.org/cmungall for details
sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

# command to run tests
script: cd src/ontology && ./run.sh make

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
    - test-travis
