name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  testbox:
    runs-on: ubuntu-latest
    env:
      working-directory: src/ontology
    container:
      image: obolibrary/odkfull
    steps:  
    - name: all
      run: make all
      working-directory: ${{env.working-directory}}
    - name: prepare_release
      run: make prepare_release
      working-directory: ${{env.working-directory}}
    - name: vocabulary
      run: make vocab
      working-directory: ${{env.working-directory}}
