name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  testbox:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src/ontology
    container:
      image: obolibrary/odkfull
    steps:  
    - name: all
      run: pwd && make all
    - name: prepare_release
      run: make prepare_release
    - name: vocabulary
      run: make vocab
