name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  testbox:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/ontology
    container:
      image: obolibrary/odkfull
    steps:
    - uses: actions/checkout@v1
    - name: all
      run: make all
    - name: release
      run: make release
    - name: vocabulary
      run: make vocab
