name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  testbox:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/ontology
    container:
      image: obolibrary/odkfull
    steps:
    - uses: actions/checkout@v2
    - name: prepare_release
      run: make prepare_release
    - name: vocabulary
      run: make vocab
    - name: Release on github
      run: |
        git config --global user.name 'engapa-bot'
        git config --global user.email 'engapa-bot@engapa.github.com'
        git commit -am "Release new ontology version"
        git push
